name: Deploy NestJS Application

on:
  push:
    tags:
      - "deploy-*"

defaults:
  run:
    working-directory: ./nest-auth-ms

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Vérifie le code du dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # Configure Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    # Installe les dépendances
    - name: Install dependencies
      run: npm install

    # Exécute les tests
    - name: Run tests
      run: npm run test

    # Déploie sur le VPS
    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_USER: ${{ secrets.VPS_USER }}
      run: |
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -r . $VPS_USER@$VPS_HOST:~
